In [1]:
import os
import pandas as pd 

# load preprocessed dataset 
data=pd.read_csv("raw_attack_data.csv")

##check if data_train has both attack (1) and normal (0) flows 
print(data['Label'].value_counts())

No Label    12418
Name: Label, dtype: int64

In [2]:
data_new=data.replace(to_replace ="No Label",value =1)

In [3]:
data_new.head(1)

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,205.185.216.10-10.0.2.4-80-50583-6,10.0.2.4,50583,205.185.216.10,80,6,08/01/2021 11:19:43 PM,60087844,4,3,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [4]:
# iterating the columns with their indices
for idx ,col in enumerate(data_new.columns): 
    print(str(idx) + " " + str(col))

0 Flow ID
1 Src IP
2 Src Port
3 Dst IP
4 Dst Port
5 Protocol
6 Timestamp
7 Flow Duration
8 Tot Fwd Pkts
9 Tot Bwd Pkts
10 TotLen Fwd Pkts
11 TotLen Bwd Pkts
12 Fwd Pkt Len Max
13 Fwd Pkt Len Min
14 Fwd Pkt Len Mean
15 Fwd Pkt Len Std
16 Bwd Pkt Len Max
17 Bwd Pkt Len Min
18 Bwd Pkt Len Mean
19 Bwd Pkt Len Std
20 Flow Byts/s
21 Flow Pkts/s
22 Flow IAT Mean
23 Flow IAT Std
24 Flow IAT Max
25 Flow IAT Min
26 Fwd IAT Tot
27 Fwd IAT Mean
28 Fwd IAT Std
29 Fwd IAT Max
30 Fwd IAT Min
31 Bwd IAT Tot
32 Bwd IAT Mean
33 Bwd IAT Std
34 Bwd IAT Max
35 Bwd IAT Min
36 Fwd PSH Flags
37 Bwd PSH Flags
38 Fwd URG Flags
39 Bwd URG Flags
40 Fwd Header Len
41 Bwd Header Len
42 Fwd Pkts/s
43 Bwd Pkts/s
44 Pkt Len Min
45 Pkt Len Max
46 Pkt Len Mean
47 Pkt Len Std
48 Pkt Len Var
49 FIN Flag Cnt
50 SYN Flag Cnt
51 RST Flag Cnt
52 PSH Flag Cnt
53 ACK Flag Cnt
54 URG Flag Cnt
55 CWE Flag Count
56 ECE Flag Cnt
57 Down/Up Ratio
58 Pkt Size Avg
59 Fwd Seg Size Avg
60 Bwd Seg Size Avg
61 Fwd Byts/b Avg
62 Fwd Pkts/b Avg
63 Fwd Blk Rate Avg
64 Bwd Byts/b Avg
65 Bwd Pkts/b Avg
66 Bwd Blk Rate Avg
67 Subflow Fwd Pkts
68 Subflow Fwd Byts
69 Subflow Bwd Pkts
70 Subflow Bwd Byts
71 Init Fwd Win Byts
72 Init Bwd Win Byts
73 Fwd Act Data Pkts
74 Fwd Seg Size Min
75 Active Mean
76 Active Std
77 Active Max
78 Active Min
79 Idle Mean
80 Idle Std
81 Idle Max
82 Idle Min
83 Label

In [5]:
# dropping passed columns 
data_new.drop(data_new.columns[[0,1,2,3,4,5,6,40]], axis = 1, inplace = True) 
data_new.head(2)

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,60087844,4,3,280.0,189.0,280.0,0.0,70.0,140.0,189.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,31868,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [6]:
#drop nan values
import numpy as np
final_data= data_new.replace([np.inf, -np.inf, "Infinity"], np.nan).dropna(axis=0, how ='any')
# comparing sizes of data frames 
print("Old data frame length:", len(data), "\nNew data frame length:",len(final_data), "\nNumber of rows with at least 1 NA value: ",(len(data)-len(final_data)))

Old data frame length: 12418
New data frame length: 12337
Number of rows with at least 1 NA value:  81

In [ ]:
tempo=final_data
#replace negatives with zeros
tempo[tempo < float(0)] = 0
tempo.to_csv('cleandata.csv',index=False, header=True)

In [9]:
tempo.head(2)

,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,60087844,4,3,280.0,189.0,280.0,0.0,70.0,140.0,189.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,31868,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [10]:
tempo.shape

(12337, 76)

In [11]:
# iterating the columns with their indices
for idx ,col in enumerate(tempo.columns): 
    print(str(idx) + " " + str(col))

0 Flow Duration
1 Tot Fwd Pkts
2 Tot Bwd Pkts
3 TotLen Fwd Pkts
4 TotLen Bwd Pkts
5 Fwd Pkt Len Max
6 Fwd Pkt Len Min
7 Fwd Pkt Len Mean
8 Fwd Pkt Len Std
9 Bwd Pkt Len Max
10 Bwd Pkt Len Min
11 Bwd Pkt Len Mean
12 Bwd Pkt Len Std
13 Flow Byts/s
14 Flow Pkts/s
15 Flow IAT Mean
16 Flow IAT Std
17 Flow IAT Max
18 Flow IAT Min
19 Fwd IAT Tot
20 Fwd IAT Mean
21 Fwd IAT Std
22 Fwd IAT Max
23 Fwd IAT Min
24 Bwd IAT Tot
25 Bwd IAT Mean
26 Bwd IAT Std
27 Bwd IAT Max
28 Bwd IAT Min
29 Fwd PSH Flags
30 Bwd PSH Flags
31 Fwd URG Flags
32 Bwd URG Flags
33 Bwd Header Len
34 Fwd Pkts/s
35 Bwd Pkts/s
36 Pkt Len Min
37 Pkt Len Max
38 Pkt Len Mean
39 Pkt Len Std
40 Pkt Len Var
41 FIN Flag Cnt
42 SYN Flag Cnt
43 RST Flag Cnt
44 PSH Flag Cnt
45 ACK Flag Cnt
46 URG Flag Cnt
47 CWE Flag Count
48 ECE Flag Cnt
49 Down/Up Ratio
50 Pkt Size Avg
51 Fwd Seg Size Avg
52 Bwd Seg Size Avg
53 Fwd Byts/b Avg
54 Fwd Pkts/b Avg
55 Fwd Blk Rate Avg
56 Bwd Byts/b Avg
57 Bwd Pkts/b Avg
58 Bwd Blk Rate Avg
59 Subflow Fwd Pkts
60 Subflow Fwd Byts
61 Subflow Bwd Pkts
62 Subflow Bwd Byts
63 Init Fwd Win Byts
64 Init Bwd Win Byts
65 Fwd Act Data Pkts
66 Fwd Seg Size Min
67 Active Mean
68 Active Std
69 Active Max
70 Active Min
71 Idle Mean
72 Idle Std
73 Idle Max
74 Idle Min
75 Label